<?php
/**
 * @file
 * Provide primary Drupal hook implementations.
 *
 * @author Jimmy Berry ("boombatower", http://drupal.org/user/214218)
 */

worker_include('plugins');

/**
 * Load a worker include file.
 *
 * @param $include
 *   Name of include file, exluding the .inc.
 */
function worker_include($include) {
  require_once drupal_get_path('module', 'worker') . '/includes/' . $include . '.inc';
}
